role:
  manager: "manager"
  admin: "admin"
  user: "user"
user: 
  per_page: 10
  image_max_size: 5242880
  size: 50
  size_big: 250
  image_accept: "image/jpeg,image/gif,image/png"
  name_max_length: 50
  email_max_length: 255
  phone_number_max_length: 15
  min_password: 6
category:
  per_page: 10
  name_max_length: 255 
product:
  name_max_length: 50
  description_max_length: 1000
  area_rows: 3
  image_accept: "image/jpeg,image/gif,image/png"
  size: 50
  image_max_size: 5242880
  size_small: "230x250"
  size_big: "250x300"
  per_page: 12
  image_max_size: 5242880
  precision: 0
suggestion:
  per_page: 10
  image_accept: "image/jpeg,image/gif,image/png"
  size: 50
  image_max_size: 542880
  area_rows: 3
  name_max_length: 100
  description_max_length: 1000
status:
  processing: "processing"
  rejected: "rejected"
  accepted: "accepted"
cart:
  init_quantity: 1
  quantity: "quantity"
  minimum_quantity: 1
  size: 150
